import type { AdminTaskRow } from "@/lib/tasks/types";

const now = new Date().toISOString();
const today = new Date().toISOString().slice(0, 10);

/** Demo tasks when Supabase is unavailable or table missing. */
export const FALLBACK_ADMIN_TASKS: AdminTaskRow[] = [
  {
    id: "demo-0001",
    title: "Follow up with Neil about final trash removal",
    description: "Confirm scope completion and whether a return visit is needed.",
    status: "Open",
    priority: "High",
    category: "Job Follow-Up",
    due_date: today,
    due_time: null,
    assigned_crew_member_id: null,
    client_id: null,
    job_id: null,
    quote_id: null,
    invoice_id: null,
    internal_notes: null,
    completed_at: null,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-0002",
    title: "Send invoice payment reminder",
    description: "Friendly reminder with Zelle / card options once configured.",
    status: "Open",
    priority: "Normal",
    category: "Invoice Follow-Up",
    due_date: today,
    due_time: null,
    assigned_crew_member_id: null,
    client_id: null,
    job_id: null,
    quote_id: null,
    invoice_id: null,
    internal_notes: null,
    completed_at: null,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-0003",
    title: "Restock microfiber towels",
    description: "Ops depot — check loadout bins for detailing crews.",
    status: "Open",
    priority: "Normal",
    category: "Supplies / Inventory",
    due_date: today,
    due_time: null,
    assigned_crew_member_id: null,
    client_id: null,
    job_id: null,
    quote_id: null,
    invoice_id: null,
    internal_notes: null,
    completed_at: null,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-0004",
    title: "Upload before/after photos from move-out clean",
    description: "Attach to job record for manager sign-off.",
    status: "In Progress",
    priority: "High",
    category: "Cleaning Job",
    due_date: today,
    due_time: null,
    assigned_crew_member_id: null,
    client_id: null,
    job_id: null,
    quote_id: null,
    invoice_id: null,
    internal_notes: null,
    completed_at: null,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-0005",
    title: "Call Square/Zelle setup for PBPP payments",
    description: "Owner admin — document merchant account for invoice CTAs.",
    status: "Waiting",
    priority: "Urgent",
    category: "Admin",
    due_date: new Date(Date.now() - 86400000).toISOString().slice(0, 10),
    due_time: null,
    assigned_crew_member_id: null,
    client_id: null,
    job_id: null,
    quote_id: null,
    invoice_id: null,
    internal_notes: null,
    completed_at: null,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-0006",
    title: "Schedule pressure washing quote",
    description: "Request photos of driveways and pool deck; send written scope.",
    status: "Open",
    priority: "Normal",
    category: "Quote Follow-Up",
    due_date: new Date(Date.now() + 2 * 86400000).toISOString().slice(0, 10),
    due_time: null,
    assigned_crew_member_id: null,
    client_id: null,
    job_id: null,
    quote_id: null,
    invoice_id: null,
    internal_notes: null,
    completed_at: null,
    archived: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-0007",
    title: "Review crew payout for completed job",
    description: "Verify hours and split before marking payout pending.",
    status: "Open",
    priority: "High",
    category: "Crew",
    due_date: new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10),
    due_time: null,
    assigned_crew_member_id: null,
    client_id: null,
    job_id: null,
    quote_id: null,
    invoice_id: null,
    internal_notes: null,
    completed_at: null,
    archived: false,
    created_at: now,
    updated_at: now,
  },
];
