import type { OpsSnapshot } from "@/lib/ops/types";

export const opsSnapshot: OpsSnapshot = {
  contacts: [
    {
      id: "contact_ellington",
      name: "Ellington Realty Group",
      type: "realtor",
      phone: "561-555-0194",
      email: "ops@ellington.example",
      lifetimeValue: 18450,
      tags: ["listing prep", "realtor sensitive", "luxury"],
      lastInteraction: "2026-05-09",
    },
    {
      id: "contact_marin",
      name: "Marin Family Office",
      type: "property-manager",
      phone: "561-555-0128",
      email: "properties@marin.example",
      lifetimeValue: 32600,
      tags: ["recurring care", "estate", "maintenance"],
      lastInteraction: "2026-05-08",
    },
    {
      id: "contact_sloan",
      name: "Sloan Residence",
      type: "homeowner",
      phone: "561-555-0149",
      email: "home@sloan.example",
      lifetimeValue: 4200,
      tags: ["move-out", "windows"],
      lastInteraction: "2026-05-07",
    },
  ],
  jobs: [
    {
      id: "job_palm_estate",
      clientId: "contact_ellington",
      propertyName: "Palm Beach Listing Prep",
      address: "Palm Beach, FL",
      serviceLine: "Listing Prep",
      status: "quoted",
      quotedAmount: 1850,
      invoiceAmount: 0,
      estimatedLaborHours: 18,
      actualLaborHours: 0,
      crewSize: 4,
      scheduledFor: "2026-05-13",
      source: "walkthrough",
    },
    {
      id: "job_marin_recurring",
      clientId: "contact_marin",
      propertyName: "Marin Estate Monthly Care",
      address: "Palm Beach Gardens, FL",
      serviceLine: "Recurring Care",
      status: "scheduled",
      quotedAmount: 2400,
      invoiceAmount: 2400,
      estimatedLaborHours: 24,
      actualLaborHours: 22,
      crewSize: 4,
      scheduledFor: "2026-05-16",
      source: "recurring",
    },
    {
      id: "job_sloan_moveout",
      clientId: "contact_sloan",
      propertyName: "Sloan Move-Out",
      address: "Jupiter, FL",
      serviceLine: "Move-Out Clean",
      status: "paid",
      quotedAmount: 780,
      invoiceAmount: 825,
      estimatedLaborHours: 9,
      actualLaborHours: 9.5,
      crewSize: 2,
      scheduledFor: "2026-05-06",
      source: "website",
    },
    {
      id: "job_ocean_pressure",
      clientId: "contact_ellington",
      propertyName: "Oceanfront Exterior Reset",
      address: "Juno Beach, FL",
      serviceLine: "Pressure Washing",
      status: "active",
      quotedAmount: 1450,
      invoiceAmount: 0,
      estimatedLaborHours: 12,
      actualLaborHours: 6,
      crewSize: 3,
      scheduledFor: "2026-05-11",
      source: "referral",
    },
  ],
  revenue: [
    {
      id: "rev_sloan",
      jobId: "job_sloan_moveout",
      date: "2026-05-07",
      amount: 825,
      category: "Move-Out Clean",
      recurring: false,
      paymentStatus: "paid",
    },
    {
      id: "rev_marin",
      jobId: "job_marin_recurring",
      date: "2026-05-16",
      amount: 2400,
      category: "Recurring Care",
      recurring: true,
      paymentStatus: "pending",
    },
    {
      id: "rev_pressure",
      jobId: "job_ocean_pressure",
      date: "2026-05-11",
      amount: 1450,
      category: "Pressure Washing",
      recurring: false,
      paymentStatus: "pending",
    },
  ],
  expenses: [
    {
      id: "exp_labor_sloan",
      date: "2026-05-07",
      amount: 285,
      category: "labor",
      vendor: "Crew payroll",
      jobId: "job_sloan_moveout",
      recurring: false,
    },
    {
      id: "exp_supplies",
      date: "2026-05-05",
      amount: 164,
      category: "supplies",
      vendor: "Janitorial supplier",
      recurring: false,
    },
    {
      id: "exp_software",
      date: "2026-05-01",
      amount: 89,
      category: "software",
      vendor: "Operations tools",
      recurring: true,
    },
    {
      id: "exp_fuel",
      date: "2026-05-08",
      amount: 126,
      category: "fuel",
      vendor: "Fleet fuel",
      recurring: false,
    },
  ],
  labor: [
    {
      id: "labor_sloan_1",
      jobId: "job_sloan_moveout",
      crewMember: "Lead Tech",
      hours: 5,
      hourlyCost: 32,
    },
    {
      id: "labor_sloan_2",
      jobId: "job_sloan_moveout",
      crewMember: "Detail Tech",
      hours: 4.5,
      hourlyCost: 28,
    },
    {
      id: "labor_pressure_1",
      jobId: "job_ocean_pressure",
      crewMember: "Exterior Lead",
      hours: 6,
      hourlyCost: 34,
    },
  ],
};
