/** Curated media manifest — generated by `npm run media:curate`. */

/** Visual story progression for PBPP transformation storytelling. */
export type StoryPhase = "neglected" | "active-work" | "restored";

export type StoryArc = {
  neglected: CuratedImage[];
  activeWork: CuratedClip[];
  restored: CuratedImage[];
};

export type MediaRole =
  | "hero"
  | "featured-transformation"
  | "gallery"
  | "detail"
  | "action"
  | "before"
  | "after"
  | "poster";

export type CuratedImage = {
  id: string;
  src: string;
  blurDataURL?: string;
  width: number;
  height: number;
  aspect: number;
  alt: string;
  score: number;
  role: MediaRole;
  storyPhase?: StoryPhase;
  focal?: string;
  originalName: string;
};

export type CuratedClip = {
  id: string;
  src: string;
  poster: string;
  width: number;
  height: number;
  durationSec: number;
  alt: string;
  score: number;
  role: "hero-loop" | "highlight" | "reel" | "social-vertical";
  originalName: string;
};

export type BeforeAfterPair = {
  id: string;
  before: CuratedImage;
  after: CuratedImage;
  contrastScore: number;
  label: string;
};

export type CuratedProject = {
  id: string;
  title: string;
  summary: string;
  location: string;
  division: "exterior" | "interior" | "property-support";
  tags: string[];
  rankedScore: number;
  timeframe?: string;
  scope: string[];
  beforeAfter: BeforeAfterPair[];
  gallery: CuratedImage[];
  heroCandidates: CuratedImage[];
  detailShots: CuratedImage[];
  actionShots: CuratedImage[];
  clips: CuratedClip[];
  storyArc: StoryArc;
};

export type CuratedManifest = {
  version: 1;
  generatedAt: string;
  hasAuthenticMedia: boolean;
  projects: CuratedProject[];
  homepage: {
    heroImage: CuratedImage | null;
    heroClip: CuratedClip | null;
    featuredTransformation: BeforeAfterPair | null;
    featuredProjectIds: string[];
    storyArc: StoryArc | null;
  };
};

export type ProjectMetadata = {
  title?: string;
  location?: string;
  division?: CuratedProject["division"];
  tags?: string[];
  timeframe?: string;
  scope?: string[];
  summary?: string;
};

export type ScoredSourceImage = {
  absolutePath: string;
  relativePath: string;
  fileName: string;
  folder: "before" | "after" | "videos" | "drone" | "root";
  width: number;
  height: number;
  aspect: number;
  brightness: number;
  sharpness: number;
  score: number;
  roles: MediaRole[];
  storyPhase: StoryPhase;
  exifDate?: string;
};

export type ScoredSourceVideo = {
  absolutePath: string;
  relativePath: string;
  fileName: string;
  folder: "videos" | "drone" | "root";
  width: number;
  height: number;
  durationSec: number;
  score: number;
  hasAudio: boolean;
};
