"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { PROSPECT_TYPE_LABELS } from "@/lib/admin/outreach/constants";
import {
  approveAndSendEnrollment,
  rejectEnrollment,
} from "@/lib/autopilot/actions/outreach-autopilot";
import type { PendingOutreachDraft } from "@/lib/autopilot/engines/outreach-engine";

export function OutreachAutopilotPanel({ initial }: { initial: PendingOutreachDraft[] }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState("");
  const [expandedId, setExpandedId] = useState<string | null>(null);

  function refresh() {
    router.refresh();
  }

  function approve(id: string) {
    if (!confirm("Send this email to the prospect?")) return;
    startTransition(async () => {
      try {
        setError("");
        await approveAndSendEnrollment(id);
        refresh();
      } catch (e) {
        setError(e instanceof Error ? e.message : "Send failed");
      }
    });
  }

  function reject(id: string) {
    if (!confirm("Reject this draft and stop the sequence for this prospect?")) return;
    startTransition(async () => {
      try {
        setError("");
        await rejectEnrollment(id);
        refresh();
      } catch (e) {
        setError(e instanceof Error ? e.message : "Reject failed");
      }
    });
  }

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <h2 className="text-lg font-bold text-navy">Outreach autopilot</h2>
          <p className="text-sm text-charcoal/60">
            Drafts generated by cron — review before send. Nothing goes out without approval.
          </p>
        </div>
        <span className="rounded-full bg-sky/50 px-3 py-1 text-xs font-bold text-navy">
          {initial.length} pending
        </span>
      </div>

      {error ? <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}

      {initial.length === 0 ? (
        <div className="admin-card text-sm text-charcoal/70">
          No drafts waiting for approval. New prospects with email are auto-enrolled on weekday
          mornings; drafts appear here when due.
        </div>
      ) : (
        <ul className="space-y-3">
          {initial.map((row) => {
            const expanded = expandedId === row.id;
            return (
              <li key={row.id} className="admin-card space-y-3">
                <div className="flex flex-wrap items-start justify-between gap-2">
                  <div>
                    <h3 className="font-bold text-navy">{row.prospect.company_name}</h3>
                    <p className="text-sm text-charcoal/70">
                      {row.prospect.contact_name ?? "No contact"} · {row.prospect.email}
                    </p>
                    <p className="mt-1 text-xs text-charcoal/55">
                      {PROSPECT_TYPE_LABELS[row.prospect.prospect_type]} · {row.sequence.name} · step{" "}
                      {row.current_step + 1}
                    </p>
                  </div>
                </div>

                <div>
                  <p className="text-xs font-semibold uppercase tracking-widest text-ocean">Subject</p>
                  <p className="mt-1 text-sm font-medium text-navy">{row.draft_subject}</p>
                </div>

                <div>
                  <p className="text-xs font-semibold uppercase tracking-widest text-ocean">Preview</p>
                  <p className="mt-1 whitespace-pre-wrap text-sm leading-relaxed text-charcoal/80">
                    {expanded
                      ? row.draft_body
                      : (row.draft_body ?? "").slice(0, 220) +
                        ((row.draft_body?.length ?? 0) > 220 ? "…" : "")}
                  </p>
                  {(row.draft_body?.length ?? 0) > 220 ? (
                    <button
                      type="button"
                      onClick={() => setExpandedId(expanded ? null : row.id)}
                      className="mt-1 text-xs font-semibold text-ocean"
                    >
                      {expanded ? "Show less" : "Show full draft"}
                    </button>
                  ) : null}
                </div>

                <div className="flex flex-wrap gap-2">
                  <button
                    type="button"
                    disabled={pending}
                    onClick={() => approve(row.id)}
                    className="admin-btn px-4 py-2 text-sm"
                  >
                    Approve & send
                  </button>
                  <button
                    type="button"
                    disabled={pending}
                    onClick={() => reject(row.id)}
                    className="admin-btn-secondary px-4 py-2 text-sm"
                  >
                    Reject
                  </button>
                </div>
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
